language: python
python:
  - "3.4"
cache: pip
install:
  - pip install -r requirements.txt
before_script:
  createdb andelabootcamp
script:
  - pytest
  - pytest --cov=diary.py

after_success:
  -coveralls
